package com.retroreadme.games.aos

import com.retroreadme.games.aos.SoulType.ABILITY
import com.retroreadme.games.aos.SoulType.BULLET
import com.retroreadme.games.aos.SoulType.ENCHANTED
import com.retroreadme.games.aos.SoulType.GUARDIAN

/**
 * All 120 souls: 110 dropped by enemies and bosses (numbered as in the in-game enemy list)
 * and 10 from soul holders. Effects and types were checked against RPGClassics' soul list;
 * areas, best farming spots and notes against Redlimit's Soul Collecting FAQ. The two agree.
 */
object AosSouls {

    private fun s(
        number: Int?, name: String, type: SoulType, effect: String, mp: String?,
        areas: String, best: String, note: String?,
    ) = Soul(
        id = "s_" + name.lowercase().replace(' ', '_').replace('-', '_').filter { it.isLetterOrDigit() || it == '_' },
        number = number, name = name, type = type, effect = effect, mp = mp,
        areas = areas, best = best, note = note,
    )

    val all: List<Soul> = listOf(
        s(1, "Bat", BULLET, "A small ring around Soma that damages enemies it touches.", "5", "Castle Corridor, Chapel, Underground Reservoir", "Room left of the 1st save point in the Corridor; several Bats.", null),
        s(2, "Zombie", ENCHANTED, "Become stronger, not weaker, when poisoned.", null, "Castle Corridor", "Any of the first few hallways in the Corridor.", null),
        s(3, "Skeleton", BULLET, "Lobs a bone upward in an arc.", "8", "Castle Corridor, Chapel, Underground Reservoir", "Long hallways in the Corridor after the 1st save point.", null),
        s(4, "Merman", BULLET, "A quick stream of water straight ahead.", "14", "Castle Corridor, Underground Reservoir", "Water pit in the room left of the 1st Corridor save point.", null),
        s(5, "Axe Armor", BULLET, "Throws an axe that returns like a boomerang.", "22", "Castle Corridor, Chapel", "Room between the 1st and 2nd Corridor saves, before the first boss room.", null),
        s(6, "Skull Archer", BULLET, "A bow appears and fires an arrow straight ahead.", "8", "Castle Corridor, Study", "Vertical room above the 2nd Corridor save point.", null),
        s(7, "Peeping Eye", ENCHANTED, "Shows which walls are breakable.", null, "Castle Corridor", "Room left of the 2nd Corridor save; enter and leave by the bottom.", null),
        s(8, "Killer Fish", BULLET, "A fish darts ahead or down at an angle; underwater use.", "16", "Castle Corridor, Underground Reservoir, Forbidden Area", "First long water corridor in the Reservoir.", null),
        s(9, "Bone Pillar", GUARDIAN, "A fiery cloud in front of Soma (hold R).", "30/sec", "Chapel, Study, Dance Hall, Floating Garden", "Open area above the first Chapel hallway.", null),
        s(10, "Blue Crow", BULLET, "A crow flies ahead, then up, and comes back.", "10", "Castle Corridor", "Vertical room above the 2nd Corridor save point.", null),
        s(11, "Buer", GUARDIAN, "Two flames circle Soma (toggle).", "5/sec", "Castle Corridor, Study", "Small room directly right of the Study save point.", null),
        s(12, "White Dragon", ENCHANTED, "CON +4.", null, "Castle Corridor, Chapel, Dance Hall", "A few rooms above and right of the 2nd Corridor save (single room).", null),
        s(13, "Zombie Soldier", BULLET, "Lobs a bouncing hand grenade.", "14", "Castle Corridor", "Long hallway above and right of the 2nd Corridor save point.", null),
        s(14, "Skeleton Knight", ENCHANTED, "STR +4.", null, "Castle Corridor, Chapel, Dance Hall", "Bottom of the small vertical room near the 3rd Corridor save point.", null),
        s(15, "Ghost", BULLET, "Two quick homing balls of holy energy.", "16", "Castle Corridor, Chapel", "First hallway of the Chapel.", null),
        s(16, "Siren", BULLET, "A music note that floats forward in a wave.", "10", "Castle Corridor", "Hallway connecting the Clock Tower to the Top Floor.", null),
        s(17, "Tiny Devil", BULLET, "Three blades that home in on enemies.", "18", "Castle Corridor, Chapel, Underground Reservoir", "Hallway leading to the 3rd Corridor save point (enter from the left).", null),
        s(18, "Durga", BULLET, "Throws a katana that passes through enemies.", "20", "Chapel, Dance Hall, Inner Quarters", "First Chapel hallway, entering from the left.", null),
        s(19, "Rock Armor", BULLET, "Lobs a rock a short distance.", "22", "Castle Corridor, Chapel, Study", "Horizontal hallway below the first Chapel hallway.", null),
        s(20, "Giant Ghost", GUARDIAN, "A barrier that reflects projectiles as holy energy (toggle).", "5/sec", "Chapel", "First vertical room at the end of the first Chapel hallway.", null),
        s(21, "Winged Skeleton", BULLET, "Lobs a spear in an arc.", "12", "Castle Corridor", "You get it during the opening sequence.", null),
        s(22, "Minotaur", ENCHANTED, "STR +8.", null, "Study, Dance Hall", "Hallway just below the upper Dance Hall save point, entering from the left.", null),
        s(23, "Student Witch", BULLET, "A cat that runs along the floor.", "20", "Study, Inner Quarters", "Inner Quarters hallway just before the Top Floor entrance.", null),
        s(24, "Arachne", BULLET, "Lobs a web ahead.", "15", "Study, Dance Hall", "First hallway in the Dance Hall.", null),
        s(25, "Fleaman", BULLET, "Releases a Fleaman that hops around.", "15", "Chapel, Dance Hall", "Hallway above the Study entrance, entering from the left.", null),
        s(26, "Evil Butcher", BULLET, "Quickly throws a knife straight ahead.", "5", "Study, Dance Hall", "Horizontal hallway up and left from the lower Dance Hall save point, entering from the right.", null),
        s(27, "Quezlcoatl", ENCHANTED, "CON +8.", null, "Chapel, Dance Hall", "Small room directly above the Dance Hall warp room.", null),
        s(28, "Ectoplasm", ENCHANTED, "Immunity to curses.", null, "Study", "Room above the Study save point.", null),
        s(29, "Catoblepas", GUARDIAN, "A cloud in front of Soma that can petrify (hold R).", "15/sec", "Study, Dance Hall", "Room up from the Study save point, entering from the right.", null),
        s(30, "Ghost Dancer", ENCHANTED, "LCK +4.", null, "Chapel, Dance Hall", "Large square room in the Dance Hall, entering from the bottom.", null),
        s(31, "Waiter Skeleton", BULLET, "Lobs a bowl of hot curry that lingers.", "30", "Dance Hall", "First hallway in the Dance Hall.", null),
        s(32, "Killer Doll", BULLET, "Throws a doll that distracts enemies.", "20", "Castle Corridor, Dance Hall, Inner Quarters", "Vertical room left of the bottom Dance Hall save, entering from the bottom left.", null),
        s(33, "Zombie Officer", ENCHANTED, "When knocked back, press A to drop straight down.", null, "Castle Corridor, Chapel, Dance Hall", "Room right of the Corridor warp room; go in and out through the warp room.", null),
        s(34, "Creaking Skull", GUARDIAN, "A giant skeletal arm swings a bone whenever you attack (toggle).", "5/sec", "Castle Corridor, Dance Hall", "The first boss drops it; later, the first stone-floored hallway to the right in the lower Dance Hall.", null),
        s(35, "Wooden Golem", ENCHANTED, "Faster MP recovery.", null, "Dance Hall", "Horizontal room below the first Dance Hall hallway, entering from the left.", null),
        s(36, "Tsuchinoko", ENCHANTED, "Hammer's shop prices drop 20%.", null, "Dance Hall", "Room left of the Big Golem boss.", "Keep leaving and re-entering until it's above ground, then kill it."),
        s(37, "Persephone", GUARDIAN, "A skeletal vacuum; each hit restores 5 HP (hold R).", "15/sec", "Inner Quarters", "Small room directly right of the Chronomage.", null),
        s(38, "Lilith", ENCHANTED, "INT +8.", null, "Inner Quarters", "Long hallway below the Inner Quarters warp room, entering from the right.", null),
        s(39, "Nemesis", BULLET, "Makes you invisible to enemies for a while.", "65", "Dance Hall, Inner Quarters", "Vertical room right of the Inner Quarters save point, entering from the bottom.", null),
        s(40, "Kyoma Demon", BULLET, "Temporary invincibility.", "80", "Inner Quarters", "Hallway right of the Inner Quarters warp room, entering from the left.", "It's the monster that appears inside certain mirrors."),
        s(41, "Chronomage", BULLET, "Stops time for everything on screen (some enemies are immune).", "96", "Inner Quarters", "Hallway right below the Inner Quarters save point.", "You need the Galamoth soul to get past it."),
        s(42, "Valkyrie", BULLET, "A ghostly swordswoman slashes upward (holy).", "50", "Inner Quarters, Clock Tower", "Room above and right of the Headhunter boss, entering from the bottom.", null),
        s(43, "Witch", GUARDIAN, "A shield in front of Soma that reflects projectiles (toggle).", "3/sec", "Inner Quarters", "The Headhunter boss room.", null),
        s(44, "Curly", GUARDIAN, "Turn into a giant Curly and rush forward (hold R).", "30/sec", "Inner Quarters", "Room right of the Headhunter boss, entering from the left.", "One of the souls that gets you through the Reservoir waterfall (with Undine)."),
        s(45, "Altair", BULLET, "Sends eagles flying straight ahead.", "22", "Floating Garden", "Room connected to the save point in the Garden's floating area.", null),
        s(46, "Red Crow", ENCHANTED, "INT +4.", null, "Floating Garden", "Top right of the Garden's four main rooms, entering from the top left.", null),
        s(47, "Cockatrice", BULLET, "A petrifying beam angled downward.", "24", "Floating Garden", "First large room in the Garden.", "Petrifies more enemies than you'd expect, including Disc Armors and most Golems."),
        s(48, "Dead Warrior", ENCHANTED, "Use a Bullet soul in the middle of a weapon attack.", null, "Floating Garden", "Bottom right of the Garden's four big rooms, entering from the bottom left.", null),
        s(49, "Devil", GUARDIAN, "Turn into a Devil and rush forward (hold R).", "30/sec", "Floating Garden, Clock Tower", "Sink into the water near the 1st Clock Tower save and go left.", "Also gets you through the Reservoir waterfall (with Undine)."),
        s(50, "Imp", GUARDIAN, "An Imp familiar that attacks enemies (toggle).", "3/sec", "Inner Quarters, Floating Garden, Underground Reservoir", "Top left of the Garden's four big rooms, entering from the top right.", null),
        s(51, "Werewolf", BULLET, "A fountain of flame that travels forward.", "28", "Floating Garden", "The first floating area near the top of the map, if you left the Garden to the left.", null),
        s(52, "Gorgon", ENCHANTED, "CON +12.", null, "Floating Garden, Underground Reservoir", "Two rooms directly below the Reservoir warp room, entering from the right.", null),
        s(53, "Disc Armor", BULLET, "A bladed disc thrown out and pulled back like a yo-yo.", "34", "Inner Quarters, Floating Garden, Clock Tower", "Room left of the 1st Clock Tower save point.", null),
        s(54, "Golem", ENCHANTED, "STR +12.", null, "Floating Garden, Clock Tower", "Second vertical room above the 1st Clock Tower save, entering from the bottom.", null),
        s(55, "Manticore", GUARDIAN, "Turn into a beast and rush forward (hold R).", "30/sec", "Floating Garden", "A boss first; later, the second floating area near the top of the map, if you left the Garden to the left.", "Also gets you through the Reservoir waterfall (with Undine)."),
        s(56, "Gremlin", ENCHANTED, "LCK +8.", null, "Clock Tower", "From the 2nd Clock Tower save, five rooms toward the 1st save (the 5th room).", null),
        s(57, "Harpy", BULLET, "Two feathers at once, one ahead and one behind.", "25", "Clock Tower, Forbidden Area", "Hallway connecting the Clock Tower to the Top Floor.", null),
        s(58, "Medusa Head", GUARDIAN, "Hover in place in mid-air (hold R).", "10/sec", "Clock Tower, Underground Reservoir, The Arena, Chaotic Realm", "Room outside the 1st Clock Tower save point.", "Lets you hover next to Balore's eye and keep hitting it."),
        s(59, "Bomber Armor", BULLET, "Lobs a big bomb that explodes after landing.", "80", "Clock Tower, Underground Reservoir", "Four rooms left of the 1st Clock Tower save point.", null),
        s(60, "Lightning Doll", BULLET, "Lightning that hits several times; can be chained.", "46", "Inner Quarters, Clock Tower, Underground Reservoir", "From the 2nd Clock Tower save, three rooms toward the 1st save.", "Often rated the best Bullet soul."),
        s(61, "Great Armor", GUARDIAN, "STR +120% while held.", "60/sec", "Clock Tower", "A boss first; later, the room outside the 2nd Clock Tower save point, exiting at the bottom.", null),
        s(62, "Une", BULLET, "Lobs an Une bud that works like a mine.", "20", "Chapel, Underground Reservoir", "Horizontal Chapel hallway below the 1st save point.", null),
        s(63, "Giant Worm", ENCHANTED, "Restores about 5 HP a second while you stand still.", null, "Underground Reservoir", "From the Reservoir warp room, four rooms toward the left save point.", null),
        s(64, "Needles", BULLET, "A Needles that explodes when touched or after a moment.", "15", "Clock Tower, Underground Reservoir", "Two rooms left of the Clock Tower warp room.", null),
        s(65, "Man-Eater", BULLET, "A slow circular laser.", "22", "Underground Reservoir", "Exit the bottom right of the large room outside the Reservoir warp room.", null),
        s(66, "Fish Head", BULLET, "A fireball straight ahead.", "18", "Underground Reservoir, Forbidden Area, Chaotic Realm", "Bottom right corner of the large square room on the far right of the Reservoir.", null),
        s(67, "Nightmare", BULLET, "A horse that charges through enemies.", "30", "Underground Reservoir", "The Reservoir room directly below the 1st Garden save point on the map.", null),
        s(68, "Triton", ENCHANTED, "STR +16.", null, "Underground Reservoir, Chaotic Realm", "Two rooms directly below the Reservoir warp room.", null),
        s(69, "Slime", BULLET, "A slimeball that bounces off walls and through enemies.", "20", "Underground Reservoir, Chaotic Realm", "Two rooms right of the Flesh Golem in the Reservoir.", null),
        s(70, "Big Golem", GUARDIAN, "A golem arm punches behind you whenever you attack (toggle).", "5/sec", "Underground Reservoir", "A boss first; later, two rooms left of the Reservoir save point.", null),
        s(71, "Dryad", BULLET, "A fruit that sprouts on enemies and drains their HP to heal you.", "33", "Underground Reservoir, Forbidden Area", "Two rooms left of the Reservoir warp room, entering from the left.", null),
        s(72, "Poison Worm", ENCHANTED, "Immunity to poison.", null, "Underground Reservoir, Forbidden Area", "Two rooms directly below the Reservoir warp room.", null),
        s(73, "Arc Demon", ENCHANTED, "2 MP for every HP of damage you take.", null, "Inner Quarters", "Top room past the Chronomage, entering from the bottom.", null),
        s(74, "Cagnazzo", GUARDIAN, "A punching demon on Soma's shoulder (toggle).", "5/sec", "Underground Cemetery, Forbidden Area", "Top right room of the Cemetery, entering from the left.", null),
        s(75, "Ripper", BULLET, "A knife that sticks in enemies for extra damage.", "35", "Floating Garden, Underground Cemetery", "Room connected to the save point in the Garden's floating area.", null),
        s(76, "Werejaguar", BULLET, "A powerful straight punch.", "40", "Underground Cemetery, Forbidden Area", "First room of the Cemetery, entering from the left.", null),
        s(77, "Ukoback", BULLET, "A fire that hangs in mid-air for a while.", "12", "Underground Reservoir", "Vertical room just before the Underground Cemetery entrance.", null),
        s(78, "Alura Une", GUARDIAN, "Rapidly restores HP while held.", "60/sec", "Underground Cemetery, Forbidden Area", "Second room of the Cemetery, entering from the left.", null),
        s(79, "Biphron", BULLET, "A row of flame pillars ahead of Soma.", "35", "Underground Cemetery", "First room of the Cemetery, entering from the left.", null),
        s(80, "Mandragora", BULLET, "Damages every enemy on screen.", "110", "Floating Garden, Underground Reservoir", "Room directly below the Reservoir warp room.", "Kill it while it's out of the ground, right before it screams."),
        s(81, "Flesh Golem", ENCHANTED, "Rotten Meat and Spoiled Milk heal you instead.", null, "Underground Reservoir", "Small room to the right, directly above the Reservoir waterfall.", null),
        s(82, "Sky Fish", GUARDIAN, "Boosts LCK and STR for a moment.", "60/sec", "Underground Reservoir", "Two rooms left of the Reservoir save point.", "It's the streak of light that flies past. Use the Chronomage soul to slow it down."),
        s(83, "Dead Crusader", ENCHANTED, "CON +16.", null, "Underground Reservoir, The Arena, Chaotic Realm", "Vertical room directly above the room outside the Arena warp room.", null),
        s(84, "Kicker Skeleton", ABILITY, "Press Down + A after a double jump for a jump kick.", null, "Floating Garden", "Outside the save point in the Garden's floating area.", "The only Ability soul that drops from an enemy."),
        s(85, "Weretiger", BULLET, "A powerful rising uppercut.", "40", "The Arena", "Long hallway at the very top of the Arena (entrance on the left only).", null),
        s(86, "Killer Mantle", BULLET, "Swaps some enemies' HP and MP.", "19", "The Arena", "Room outside the Arena save point.", "Kills Iron Golems and Red Minotaurs in one hit, but heals some enemies a lot."),
        s(87, "Mudman", BULLET, "Lobs a ball of mud in a wide arc.", "20", "Forbidden Area", "First hallway in the Forbidden Area.", null),
        s(88, "Gargoyle", ENCHANTED, "Immunity to petrification.", null, "Chapel, Underground Reservoir, The Arena, Top Floor, Forbidden Area", "Second room of the Arena, entering from the bottom right.", null),
        s(89, "Red Minotaur", BULLET, "A huge axe swings forward in a circle.", "150", "The Arena, Top Floor", "Middle level of the large open area of the Top Floor, entering from the right.", "Killer Mantle kills them in one hit."),
        s(90, "Beam Skeleton", BULLET, "A flame beam about a third of the screen long.", "28", "The Arena, Chaotic Realm", "Third Arena challenge by the save point (the third, bottom door).", null),
        s(91, "Alastor", GUARDIAN, "A sword familiar that attacks enemies (toggle).", "3/sec", "Chaotic Realm", "A few rooms before the 2nd Chaotic Realm save point, entering from the bottom.", null),
        s(92, "Skull Millione", BULLET, "A poisoned slash straight ahead.", "25", "The Arena", "Room outside the Arena warp room, entering from the right.", null),
        s(93, "Giant Skeleton", BULLET, "Lobs a huge skull.", "19", "The Arena, Chaotic Realm", "A few rooms before the 2nd Realm save, in the room left of the Gladiator and Basilisk.", null),
        s(94, "Gladiator", BULLET, "Lobs a wheel that rolls along the floor.", "30", "The Arena, Chaotic Realm", "Two rooms right of the Arena warp room.", null),
        s(95, "Bael", ENCHANTED, "INT +12.", null, "The Arena, Top Floor", "Square room up and left from the Top Floor warp room, entering from the bottom.", null),
        s(96, "Succubus", ENCHANTED, "Recover 5 HP for every hit you land.", null, "The Arena, Top Floor, Chaotic Realm", "Small room two rooms up from the Arena save point.", "Needed for the good and best endings."),
        s(97, "Mimic", ENCHANTED, "5 gold for every HP of damage you take.", null, "Forbidden Area, Dance Hall, Chaotic Realm", "The Joyeuse sword room at the end of the path past the ship in the Forbidden Area.", null),
        s(98, "Stolas", ENCHANTED, "INT +16.", null, "Top Floor, Chaotic Realm", "From the Top Floor warp room, up and left three rooms.", null),
        s(99, "Erinys", ENCHANTED, "120% experience.", null, "The Arena, Top Floor, Chaotic Realm", "Second Arena challenge by the save point (the second door).", null),
        s(100, "Lubicant", ENCHANTED, "The lower your HP, the higher your STR.", null, "The Arena, Top Floor, Chaotic Realm", "First Arena challenge by the save point (the top door).", null),
        s(101, "Basilisk", ENCHANTED, "DEF up, STR down.", null, "Top Floor, Chaotic Realm", "Bottom of the large open room on the Top Floor, entering from the right.", null),
        s(102, "Iron Golem", ENCHANTED, "Soma no longer flinches when hit.", null, "Top Floor, Chaotic Realm", "Room below the large open area of the Top Floor, beside the Hippogryph soul.", "Killer Mantle kills it in one hit."),
        s(103, "Demon Lord", BULLET, "A large fire orb straight ahead.", "38", "Chaotic Realm", "Rooms near the 2nd and 3rd Chaotic Realm save points.", null),
        s(104, "Final Guard", GUARDIAN, "A shield that blocks frontal attacks (hold R).", "60/sec", "Top Floor, Chaotic Realm", "Single room shortly after the 2nd Realm save, left in the elevator shaft.", null),
        s(105, "Flame Demon", BULLET, "Three fireballs straight ahead.", "44", "Underground Cemetery, Forbidden Area", "First room of the Cemetery, entering from the right.", "Needed for the good and best endings."),
        s(106, "Shadow Knight", GUARDIAN, "A Shadow Knight slashes ahead whenever you attack (toggle).", "5/sec", "Chaotic Realm", "A few rooms below the final save point.", null),
        s(107, "Headhunter", ENCHANTED, "All stats but LCK rise with the number of souls you've collected.", null, "Inner Quarters", "Defeat the Headhunter boss.", "Every 16 souls collected (duplicates count) makes it stronger, up to +33."),
        s(108, "Death", GUARDIAN, "Scythes keep appearing and attacking (toggle).", "10/sec", "Clock Tower", "Defeat Death.", "Great cover against Medusa Heads and Fleamen."),
        s(109, "Legion", BULLET, "Tentacles fire lasers ahead.", "66", "Underground Cemetery", "Defeat Legion.", "It only drops its soul if you knock off all four sections of its shell before destroying the core. Missed it? New Game+ gives you another chance."),
        s(110, "Balore", BULLET, "An extremely powerful straight punch.", "120", "The Arena", "Defeat Balore.", null),
        s(null, "Giant Bat", GUARDIAN, "Turn into a bat and fly; getting hit turns you back (toggle).", "30/sec", "The Arena", "Soul holder in the room after the Balore fight.", "Needed for the good and best endings."),
        s(null, "Flying Armor", GUARDIAN, "Fall slower after a jump, so you jump further (hold R).", "5/sec", "Castle Corridor", "Soul holder at the end of the 2nd long water passage.", null),
        s(null, "Black Panther", GUARDIAN, "Dash with a damaging shock wave (hold R).", "2/sec", "Top Floor", "Soul holder in the room after the Graham fight.", null),
        s(null, "Skula", ENCHANTED, "Sink and walk underwater.", null, "Clock Tower", "Soul holder in the room after the Death fight.", null),
        s(null, "Undine", ENCHANTED, "Walk on water.", null, "Inner Quarters", "Soul holder above and right of the Headhunter boss; zig-zag up the large room.", null),
        s(null, "Grave Keeper", ABILITY, "Backdash with L.", null, "Castle Corridor", "Soul holder on the only path from the start.", null),
        s(null, "Skeleton Blaze", ABILITY, "Slide with Down + A.", null, "Dance Hall", "Soul holder in the room after the Big Golem fight.", null),
        s(null, "Malphas", ABILITY, "Double jump.", null, "Study", "Soul holder in the room after Great Armor, where you meet Hammer.", null),
        s(null, "Hippogryph", ABILITY, "Super-high jump (Up + L, or L in mid-air).", null, "Top Floor", "Soul holder behind the breakable wall right of the Iron Golem.", null),
        s(null, "Galamoth", ABILITY, "See through the Chronomage's time stop, so you can get past it.", null, "Underground Cemetery", "Soul holder a few rooms right of the Legion fight; sink into the water with Skula and head right.", null),
    ).sortedWith(compareBy({ it.type.ordinal }, { it.name }))

    val byId: Map<String, Soul> = all.associateBy { it.id }
}
