"""Generates a game's map data Kotlin file from its area files.

    python tools/metroid-maps/gen.py mzm      # -> app/.../games/mzm/MzmMapData.kt
    python tools/metroid-maps/gen.py mf       # -> app/.../games/mf/MfMapData.kt

Each game's settings live in games/<game>/config.py. Room codes are numbered per area in the
order the game's 100% route reaches each room, starting from the room where you first enter the
area (the entry cell in the config), so codes follow play order.
"""
import collections
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parents[1] / 'app/src/main/java/com/retroreadme/games'


def load_config(game):
    ns = {}
    exec((HERE / 'games' / game / 'config.py').read_text(encoding='utf-8'), ns)
    return ns


def load_area(game, module):
    ns = {}
    exec((HERE / 'games' / game / 'areas' / f'{module}.py').read_text(encoding='utf-8'), ns)
    return ns['rooms'], ns['doors'], ns['items']


def rects(cells):
    """Splits a room's cells into as few row-run rectangles as is easy."""
    runs = []
    for r in sorted({r for c, r in cells}):
        cs = sorted(c for c, rr in cells if rr == r)
        s = p = cs[0]
        for c in cs[1:] + [None]:
            if c is not None and c == p + 1:
                p = c
                continue
            runs.append([s, r, p, r])
            if c is not None:
                s = p = c
    out = []
    for a in runs:
        for b in out:
            if b[0] == a[0] and b[2] == a[2] and b[3] + 1 == a[1]:
                b[3] = a[3]
                break
        else:
            out.append(a)
    return out


def number(rooms, items, entry, route):
    """Room index -> number, in the order the route reaches each room (then by distance)."""
    own = {c: i for i, r in enumerate(rooms) for c in r[0]}
    adj = collections.defaultdict(set)
    for (c, r), i in own.items():
        for n in ((c + 1, r), (c, r + 1)):
            j = own.get(n)
            if j is not None and j != i:
                adj[i].add(j)
                adj[j].add(i)
    key = lambda i: (min(r for c, r in rooms[i][0]), min(c for c, r in rooms[i][0]))
    order = [own[entry]]
    seen = {own[entry]}

    def path_to(t):
        prev = {s: None for s in seen}
        q = collections.deque(sorted(seen, key=key))
        while q:
            u = q.popleft()
            if u == t:
                break
            for v in sorted(adj[u], key=key):
                if v not in prev:
                    prev[v] = u
                    q.append(v)
        p = []
        u = t
        while u is not None and u not in seen:
            p.append(u)
            u = prev.get(u)
        return p[::-1]

    for t in [own[items[i]] for i in route if i in items]:
        for u in path_to(t):
            if u not in seen:
                seen.add(u)
                order.append(u)
    q = collections.deque(order[:])
    while q:
        u = q.popleft()
        for v in sorted(adj[u], key=key):
            if v not in seen:
                seen.add(v)
                order.append(v)
                q.append(v)
    for i in sorted(range(len(rooms)), key=key):
        if i not in seen:
            order.append(i)
    return {i: n + 1 for n, i in enumerate(order)}, own


STYLE = {0: "NORMAL", 1: "HIDDEN", 2: "HEATED"}
DOOR = {'n': "NORMAL", 'r': "MISSILE", 'g': "SUPER", 'y': "POWER_BOMB"}


def main():
    game = sys.argv[1]
    cfg = load_config(game)
    pkg_dir = APP / cfg['PACKAGE_DIR']
    route_src = (pkg_dir / cfg['ROUTE_FILE']).read_text(encoding='utf-8')
    route = re.findall(r'"([a-z0-9]{1,3}_[a-z]+\d*)"', route_src)
    out = [
        f"package com.retroreadme.games.{cfg['PACKAGE_DIR']}", "",
        f"// Generated by tools/metroid-maps/gen.py {game}; edit the area files there, not this file.",
        "// Room layouts transcribed from the in-game map grid (one cell = one map square).",
        "// Rooms are numbered in the order the 100% route reaches them. Never renumber a released",
        "// room code without updating the item steps that mention it.", "",
        "import com.retroreadme.ui.DoorKind.MISSILE", "import com.retroreadme.ui.DoorKind.POWER_BOMB",
        "import com.retroreadme.ui.DoorKind.SUPER", "import com.retroreadme.ui.Exit",
        "import com.retroreadme.ui.ExitDir.DOWN", "import com.retroreadme.ui.ExitDir.LEFT",
        "import com.retroreadme.ui.ExitDir.RIGHT", "import com.retroreadme.ui.ExitDir.UP",
        "import com.retroreadme.ui.RoomMap", "import com.retroreadme.ui.RoomStyle.HEATED",
        "import com.retroreadme.ui.RoomStyle.HIDDEN", "import com.retroreadme.ui.cell",
        "import com.retroreadme.ui.d", "import com.retroreadme.ui.r", "import com.retroreadme.ui.room", "",
        f"object {cfg['OBJECT']} {{", "",
    ]
    total = 0
    for key, label, prefix, module, entry in cfg['AREAS']:
        rooms, doors, items = load_area(game, module)
        code, own = number(rooms, items, entry, route)
        out.append(f"    val {module} = RoomMap(")
        out.append(f'        "{key}", "{label}", "{prefix}",')
        out.append("        rooms = listOf(")
        for i in sorted(range(len(rooms)), key=lambda i: code[i]):
            cells, sty, note = rooms[i]
            args = [f'"{prefix}-{code[i]:02d}"']
            if sty:
                args.append(STYLE[sty])
            args.append("listOf(" + ", ".join(f"r({a},{b},{c},{d})" for a, b, c, d in rects(cells)) + ")")
            for part in note.split(';'):
                if part == "save":
                    args.append("save = true")
                elif part == "map":
                    args.append("map = true")
                elif part.startswith("mark:"):
                    args.append(f'mark = "{part[5:]}"')
                elif part.startswith("elev"):
                    _, dest, d = part.split(":")
                    args.append(f'exit = Exit("{dest}", {d.upper()})')
            out.append(f"            room({', '.join(args)}),")
        out.append("        ),")
        out.append("        doors = listOf(")
        ds = [f"d({r},{c}{'' if k == 'n' else ', ' + DOOR[k]})" for r, c, k in doors]
        for j in range(0, len(ds), 8):
            out.append("            " + ", ".join(ds[j:j + 8]) + ",")
        out.append("        ),")
        out.append("        items = mapOf(")
        for iid, (c, r) in items.items():
            out.append(f'            "{iid}" to cell({c}, {r}),')
        out.append("        ),")
        out.append("    )")
        out.append("")
        total += len(items)
        print(f"{prefix}: {len(rooms)} rooms, {len(items)} items")
    out.append("    val all: List<RoomMap> = listOf(" + ", ".join(a[3] for a in cfg['AREAS']) + ")")
    out.append("}")
    (pkg_dir / cfg['OUTPUT']).write_text("\n".join(out) + "\n", encoding='utf-8')
    print(f"total items {total} -> {cfg['OUTPUT']}")


if __name__ == '__main__':
    main()
